pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:shlomisaidian/2023b.noy.tsafrir.git
          - cd RepoName.git
          - git push --mirror git@github.com:ShacharFelman/SoftDev_TravelersSuperapp.git